version: "3"

services:
  ### 
  ipservice:
    image: "i386/ubuntu"
    container_name: ipservice
    restart: always
    env_file:
      - .env
    volumes:
      - ".data/arcus:/home/reg/arcus"
    command: bash -c "
      apt-get update &&
      apt-get install tzdata &&
      rm /etc/localtime &&
      ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime &&
      apt-get install libstdc++5 &&
      cd /home/reg/arcus/ipservice &&
      ./ipservice arcus_ip_service.conf &&
      sleep 3153600000"
    ports:
      - 9301:9301
      - 9302:9302
    networks:
      n_bank_terminal_arcus:
        ipv4_address: 10.3.0.100
  #
  bank-terminal-arcus:
    image: "ubuntu:latest"
    container_name: bank-terminal-arcus
    restart: always
    env_file:
      - .env
    volumes:
      - ".data/arcus:/home/reg/arcus"
      - ".bin:/mnt/app"
    command: bash -c "
      apt-get update &&
      apt-get install tzdata &&
      rm /etc/localtime &&
      ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime &&
      cd /mnt/app &&
      ./bank-terminal-arcus"
    ports:
      - 8012:8012
    networks:
      n_bank_terminal_arcus:
        ipv4_address: 10.3.0.101
  #
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=belcoder
      - RABBITMQ_DEFAULT_PASS=qwer1331
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      n_bank_terminal_arcus:
        ipv4_address: 10.3.0.102

networks:
  #
  n_bank_terminal_arcus:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24